/*
 * Built-In User Program Lookup
 *
 * This file provides name-based lookup over the generated built-in user
 * program registry. The registry contents themselves are generated by the
 * build and linked into the kernel as ordinary data.
 */

#include <stddef.h>

#include "kernel/user_programs.h"

static int user_program_names_equal(const char *left, const char *right) {
    size_t index;

    if (left == NULL || right == NULL) {
        return 0;
    }

    for (index = 0; left[index] != '\0' || right[index] != '\0'; index++) {
        if (left[index] != right[index]) {
            return 0;
        }
    }

    return 1;
}

const struct user_program *user_program_find(const char *name) {
    size_t index;

    for (index = 0; index < builtin_user_program_count; index++) {
        if (user_program_names_equal(name, builtin_user_programs[index].name)) {
            return &builtin_user_programs[index];
        }
    }

    return NULL;
}
